test_that("lSource contains Raw_Death domain (#153)", {
  expect_true("Raw_Death" %in% names(lSource))
})

test_that("Raw_Death contains deathcls column (#153)", {
  expect_true("deathcls" %in% names(lSource$Raw_Death))
})

test_that("Raw_Death deathcls contains expected death reason values (#153, #156)", {
  # Full gsm.datasim deathcls generator vocabulary (see gsm.datasim R/Raw_Death.R).
  # The prior list held only the three reasons the pre-regen lSource happened to
  # sample; the IP non-starter regen shifts the RNG stream and can surface any of
  # the generator's reasons, so assert against the complete vocabulary.
  expected_values <- c(
    "Progressive Disease",
    "Adverse Event",
    "Disease Recurrence",
    "Not related to disease",
    "Related to long-term follow-up and not related to study drug"
  )
  actual_values <- unique(lSource$Raw_Death$deathcls)
  expect_true(all(actual_values %in% expected_values))
  expect_true(length(actual_values) > 1)
})

test_that("Raw_Death has required columns (#153)", {
  expected_cols <- c("studyid", "subjid", "death_dt", "deathcls")
  expect_true(all(expected_cols %in% names(lSource$Raw_Death)))
})

test_that("Raw_Death deathcls has no NA values (#153)", {
  expect_false(any(is.na(lSource$Raw_Death$deathcls)))
})

test_that("lSource carries the upstream IP non-starter fields (#177)", {
  drv <- c(
    "drv_enrollment_dt", "drv_ip_dosed", "drv_ip_first_dose_dt",
    "drv_enrl_first_dose_days", "drv_days_lapsed_since_enrl",
    "drv_ip_nonstarter_status"
  )
  expect_true(all(drv %in% names(lSource$Raw_SUBJ)))

  enrolled <- lSource$Raw_SUBJ[lSource$Raw_SUBJ$enrollyn == "Y", ]
  expect_true(all(enrolled$drv_ip_nonstarter_status %in% c(
    "Dosed", "Confirmed Non-Starter",
    "Potential Non-Starter outside window",
    "Potential Non-Starter within window"
  )))
})

# ---- IP non-starter scenarios (#184) ----
# End of the last snapshot generated by data-raw/simulate_longitudinal_data.R:
# gsm.datasim dates it at month end (2012-03-31) and generates 28 days from there.
as_of_date <- as.Date("2012-04-28")
is_blank <- function(x) is.na(x) | x == ""
enrolled_subj <- function() lSource$Raw_SUBJ[lSource$Raw_SUBJ$enrollyn %in% "Y", ]
enrolled_studcomp <- function() {
  subj <- enrolled_subj()
  sc <- lSource$Raw_STUDCOMP
  sc$status <- subj$drv_ip_nonstarter_status[match(sc$subjid, subj$subjid)]
  sc[!is.na(sc$status), ]
}

test_that("drv_kit_assigned is NA for non-enrolled, Y for every dosed subject and mixed otherwise (#184)", {
  subj <- lSource$Raw_SUBJ
  enrolled <- subj$enrollyn %in% "Y"
  undosed <- subj$drv_kit_assigned[enrolled & subj$drv_ip_dosed %in% "N"]

  expect_identical(is.na(subj$drv_kit_assigned), !enrolled)
  expect_true(all(subj$drv_kit_assigned[subj$drv_ip_dosed %in% "Y"] == "Y"))
  expect_gte(sum(undosed == "Y"), 3)
  expect_gte(sum(undosed == "N"), 3)
})

test_that("enrolled subjects cover all four IP non-starter statuses (#184)", {
  expect_setequal(unique(enrolled_subj()$drv_ip_nonstarter_status), c(
    "Dosed", "Confirmed Non-Starter",
    "Potential Non-Starter outside window", "Potential Non-Starter within window"
  ))
})

test_that("completion records agree with the IP non-starter status (#184)", {
  sc <- enrolled_studcomp()
  subj <- enrolled_subj()
  confirmed <- subj$subjid[subj$drv_ip_nonstarter_status == "Confirmed Non-Starter"]

  expect_true(all(confirmed %in% sc$subjid[sc$compyn %in% "N"]))
  expect_false(any(grepl("^Potential", sc$status) & !is_blank(sc$compyn)))
  expect_true(all(sc$status[sc$compyn %in% "Y"] == "Dosed"))
  expect_identical(!is_blank(sc$compreas), sc$compyn %in% "N")
})

test_that("some Confirmed non-starters withdrew consent and some dosed subjects completed (#184)", {
  sc <- enrolled_studcomp()

  expect_gte(sum(sc$status == "Confirmed Non-Starter" & sc$compreas == "Withdrew Consent"), 3)
  expect_gte(sum(sc$status == "Dosed" & sc$compyn %in% "Y"), 3)
})

test_that("completion records fall between the subject's anchor and the as-of date (#184)", {
  subj <- enrolled_subj()
  sc <- enrolled_studcomp()
  anchor <- dplyr::coalesce(subj$drv_ip_first_dose_dt, subj$drv_enrollment_dt)[match(sc$subjid, subj$subjid)]
  created <- as.Date(sc$mincreated_dts)

  expect_true(all(created >= anchor & created <= as_of_date))
})

test_that("a site has two or more counted non-starters, so kri0019 flags red (#184)", {
  subj <- enrolled_subj()
  counted <- subj$drv_ip_nonstarter_status %in% c("Confirmed Non-Starter", "Potential Non-Starter outside window")

  expect_gte(max(table(subj$invid[counted])), 2)
})

# ---- Premature treatment discontinuation (#176) ----
ptd_cols <- c(
  "drv_treatment_discontinuation_dt",
  "drv_premature_discontinuation_reason",
  "drv_days_lapsed_enrl_discontinuation"
)

test_that("Raw_SUBJ carries the three PTD fields at one row per subject (#176)", {
  subj <- lSource$Raw_SUBJ

  expect_true(all(ptd_cols %in% names(subj)))
  expect_s3_class(subj$drv_treatment_discontinuation_dt, "Date")
  expect_type(subj$drv_premature_discontinuation_reason, "character")
  expect_type(subj$drv_days_lapsed_enrl_discontinuation, "integer")
  expect_equal(anyDuplicated(subj$subjid), 0)
  expect_false("drv_premature_discont" %in% names(subj))
})

test_that("only dosed subjects carry PTD values (#176)", {
  subj <- lSource$Raw_SUBJ

  expect_true(all(is.na(subj[!subj$drv_ip_dosed %in% "Y", ptd_cols])))
})

test_that("days lapsed is NA exactly when the date is NA and otherwise counts from enrollment inclusively (#176)", {
  subj <- lSource$Raw_SUBJ
  dt <- subj$drv_treatment_discontinuation_dt
  dated <- !is.na(dt)

  expect_identical(is.na(subj$drv_days_lapsed_enrl_discontinuation), !dated)
  expect_equal(
    subj$drv_days_lapsed_enrl_discontinuation[dated],
    as.integer(dt[dated] - subj$drv_enrollment_dt[dated]) + 1L
  )
})

test_that("discontinuation dates fall between first dose and the as-of date (#176)", {
  subj <- lSource$Raw_SUBJ
  dt <- subj$drv_treatment_discontinuation_dt
  dated <- !is.na(dt)

  expect_true(all(dt[dated] >= subj$drv_ip_first_dose_dt[dated]))
  expect_true(all(dt[dated] <= as_of_date))
})

test_that("lSource covers every premature discontinuation scenario (#176)", {
  subj <- lSource$Raw_SUBJ
  d <- subj[subj$drv_ip_dosed %in% "Y", ]
  dated <- !is.na(d$drv_treatment_discontinuation_dt)
  reason <- d$drv_premature_discontinuation_reason
  sc <- lSource$Raw_STUDCOMP
  completed <- d$subjid %in% sc$subjid[sc$compyn %in% "Y"]

  expect_gte(sum(table(d$invid[dated]) >= 3), 5)
  expect_true(any(dated & is.na(reason)))
  expect_true(any(dated & grepl(",", reason)))
  expect_true(any(dated & completed))
  expect_true(any(!dated & completed))
  expect_true(any(!dated & !completed))
  expect_true(any(!dated & !is.na(reason)))
  expect_true(any(d$drv_days_lapsed_enrl_discontinuation %in% 1L))
  expect_true(any(!subj$drv_ip_dosed %in% "Y"))
})

test_that("split reasons come from the full gsm.datasim vocabulary (#176)", {
  # gsm.datasim R/Raw_SUBJ.R .ptd_reason_values, not only what this seed drew.
  vocabulary <- c(
    "Adverse Event", "Lack of Efficacy", "Physician Decision",
    "Withdrawal by Subject", "Protocol Deviation", "Progressive Disease",
    "Lost to Follow-up"
  )
  reasons <- stats::na.omit(lSource$Raw_SUBJ$drv_premature_discontinuation_reason)

  expect_true(all(trimws(unlist(strsplit(reasons, ","))) %in% vocabulary))
})
